export const adsData = [
	{
		id: 1,
		title: 'Huawei Y3 II 20/18 ',
		date: 'Post on 29 Nov 8:20 am, Tangil, Dhaka Division',
		images: ['/images/ad1/ad1_1.jpg', '/images/ad1/ad1_2.jpg'],
		price: 'TK 1,000',
		condition: 'Used',
		brand: 'Huawei',
		model: 'Y3 II',
		edition: ' y3 20/18',
		features: [
			'Bluetooth',
			'Camera',
			'Dual SIM',
			'GPS',
			'MicroSD',
			'NFC',
			'Screen',
			'Speaker',
			'WiFi',
			'WiFi Hotspot',
		],
		description: 'fresh phone charge khove valo jai akono khola hoi nai',
		category: 'Mobile',
		subCategory: 'Mobile Phones',
		userId: 1,
	},
	{
		id: 2,
		title: 'Nokia E63 . ',
		date: 'Posted on 29 Nov 8:17 am, Kafrul, Dhaka',
		images: [
			'/images/ad2/ad2_1.jpg',
			'/images/ad2/ad2_2.jpg',
			'/images/ad2/ad2_3.jpg',
			'/images/ad2/ad2_4.jpg',
			'/images/ad2/ad2_5.jpg',
		],
		price: 'TK 1,000',
		condition: 'Used',
		brand: 'Nokia',
		model: 'E63',
		edition: '',
		features: [
			'Bluetooth',
			'Camera',
			'Dual SIM',
			'GPS',
			'MicroSD',
			'NFC',
			'Screen',
			'Speaker',
			'WiFi',
			'WiFi Hotspot',
		],
		description:
			'Black color , original battery . Pls no chatting & no bargaining .',
		category: 'Mobile',
		subCategory: 'Mobile Phones',
		userId: 2,
	},
	{
		id: 3,
		title: 'Samsung Galaxy S10',
		date: 'Posted on 29 Nov 8:17 am, Kafrul, Dhaka',
		images: [
			'/images/ad3/ad3_1.jpg',
			'/images/ad3/ad3_2.jpg',
			'/images/ad3/ad3_3.jpg',
			'/images/ad3/ad3_4.jpg',
			'/images/ad3/ad3_5.jpg',
		],
		price: 'TK 1,000',
		condition: 'Used',
		brand: 'Samsung',
		model: 'Galaxy S10',
		edition: '6/128',
		features: [
			'Bluetooth',
			'Camera',
			'Dual SIM',
			'GPS',
			'MicroSD',
			'NFC',
			'Screen',
			'Speaker',
			'WiFi',
			'WiFi Hotspot',
		],
		description: 'Fresh phone charge khove valo jai akono khola hoi nai',
		category: 'Mobile',
		subCategory: 'Mobile Phones',
		userId: 3,
	},
	{
		id: 4,
		title:
			'Asus VivoBook 14-X412F,Core i7,10th Gen,12GB DDR4 Ram,512GB NVMe SSD',
		date: 'Posted on 26 Nov 11:51 am, Mohammadpur, Dhaka',
		images: [
			'/images/ad4/ad4_1.jpg',
			'/images/ad4/ad4_2.jpg',
			'/images/ad4/ad4_3.jpg',
			'/images/ad4/ad4_4.jpg',
			'/images/ad4/ad4_5.jpg',
		],
		price: 'TK 64,000',
		condition: 'Used',
		brand: 'Asus',
		model: 'VivoBook 14-X412F',
		edition: '26/11',
		features: [
			'Bluetooth',
			'Camera',
			'Dual SIM',
			'GPS',
			'MicroSD',
			'NFC',
			'Screen',
			'Speaker',
			'WiFi',
			'WiFi Hotspot',
		],
		description:
			'Asus VivoBook 14-X412F laptop with 10th Generation Intel® Core i7-10510U 12GB DDR4 Ram 512GB NVMe SSD Nvidia MX250 Dedicated Graphics +Intel UHD Graphics 620',
		category: 'Laptop',
		subCategory: 'Electronics',
		userId: 3,
	},
	{
		id: 5,
		title: 'Dell Latitude 3330, Intel Core i5',
		date: 'Posted on 29 Nov 1:21 pm, Dhanmondi, Dhaka',
		images: [
			'/images/ad5/ad5_1.jpg',
			'/images/ad5/ad5_2.jpg',
			'/images/ad5/ad5_3.jpg',
			'/images/ad5/ad5_4.jpg',
			'/images/ad5/ad5_5.jpg',
		],
		price: 'TK 17,999',
		condition: 'Used',
		brand: 'Dell',
		model: 'Latitude 3330',
		edition: '3330',
		features: [
			'Bluetooth',
			'Camera',
			'GPS',
			'MicroSD',
			'NFC',
			'Screen',
			'Speaker',
			'WiFi',
			'WiFi Hotspot',
		],
		description:
			'Dell Latitude 3330 laptop with Intel® Core i5-1035G1 10th Gen, 8GB DDR4 Ram, 512GB SSD, Intel HD Graphics 620',
		category: 'Laptop',
		subCategory: 'Electronics',
		userId: 1,
	},
	{
		id: 6,
		title: 'hp Elite book corei5-6th gen business siris american laptop',
		date: 'Posted on 22 Nov 10:12 am, Kotwali, Chattogram',
		images: [
			'/images/ad6/ad6_1.jpg',
			'/images/ad6/ad6_2.jpg',
			'/images/ad6/ad6_3.jpg',
			'/images/ad6/ad6_4.jpg',
			'/images/ad6/ad6_5.jpg',
		],
		price: 'TK  30,546',
		condition: 'Used',
		brand: 'HP',
		model: 'Elite Book',
		edition: 'Core i5-6th gen',
		features: [
			'Bluetooth',
			'Camera',
			'Dual SIM',
			'GPS',
			'MicroSD',
			'NFC',
			'Screen',
			'Speaker',
			'WiFi',
			'WiFi Hotspot',
		],
		description: 'HP Elite Book corei5-6th gen business siris american laptop',
		category: 'Laptop',
		subCategory: 'Electronics',
		userId: 2,
	},
	{
		id: 7,
		title: 'Desktop computer',
		date: 'Posted on 29 Nov 1:18 pm, Savar, Dhaka',
		images: [
			'/images/ad7/ad7_1.jpg',
			'/images/ad7/ad7_2.jpg',
			'/images/ad7/ad7_3.jpg',
			'/images/ad7/ad7_4.jpg',
		],
		price: 'TK  30,546',
		condition: 'Used',
		brand: 'Other brand',
		model: 'Other model',
		edition: 'Other edition',
		features: [
			'Bluetooth',
			'Camera',
			'Dual SIM',
			'GPS',
			'MicroSD',
			'NFC',
			'Screen',
			'Speaker',
			'WiFi',
			'WiFi Hotspot',
		],
		description:
			'Ram 8  power button problem. Other all ok. Real buyer knok and phone',
		category: 'Desktop',
		subCategory: 'Electronics',
		userId: 3,
	},
	{
		id: 8,
		title: 'Samsung 40" Non-smart TV (Fresh)',
		date: 'Posted on 21 Nov 11:02 pm, Mirpur, Dhaka',
		images: [
			'/images/ad8/ad8_1.jpg',
			'/images/ad8/ad8_2.jpg',
			'/images/ad8/ad8_3.jpg',
			'/images/ad8/ad8_4.jpg',
			'/images/ad8/ad8_5.jpg',
		],
		price: 'TK  25,546',
		condition: 'Used',
		brand: 'Samsung',
		model: '40" Non-smart TV',
		edition: 'Fresh',
		features: [
			'Bluetooth',
			'Camera',
			'Dual SIM',
			'GPS',
			'MicroSD',
			'NFC',
			'Screen',
			'Speaker',
			'WiFi',
			'WiFi Hotspot',
		],
		description: 'Samsung 40" Non-smart TV (Fresh)',
		category: 'TV',
		subCategory: 'Electronics',
		userId: 1,
	},
	{
		id: 9,
		title: 'TV KELON 40 INCH SMART',
		date: 'Posted on 02 Nov 1:03 pm, Mirpur, Dhaka',
		images: ['/images/ad9/ad9_1.jpg'],
		price: 'TK  17,500',
		condition: 'New',
		brand: 'KELON',
		model: '40 INCH SMART',
		edition: 'Fresh',
		features: [],
		description: 'TV KELON 40 INCH SMART',
		category: 'TV',
		subCategory: 'Electronics',
		userId: 2,
	},
	{
		id: 10,
		title:
			'Disnie Italy brand Multi-function Digital Convection 52L Electric Oven',
		date: 'Posted on 28 Oct 12:31 pm, Chaukbazar, Dhaka',
		images: ['/images/ad10/ad10_1.jpg'],
		price: 'TK  9,500',
		condition: 'New',
		brand: 'Disnie',
		model: 'Multi-function Digital Convection 52L',
		edition: 'Fresh',
		features: [],
		description:
			'Disnie Italy brand Multi-function Digital Convection 52L Electric Oven',
		category: 'Oven',
		subCategory: 'Home & Living',
		userId: 3,
	},
	{
		id: 11,
		title: 'Bajaj Platina 2018',
		date: 'Posted on 23 Nov 12:15 pm, Mirpur, Dhaka',
		images: [
			'/images/ad11/ad11_1.jpg',
			'/images/ad11/ad11_2.jpg',
			'/images/ad11/ad11_3.jpg',
			'/images/ad11/ad11_4.jpg',
			'/images/ad11/ad11_5.jpg',
			'/images/ad11/ad11_6.jpg',
			'/images/ad11/ad11_7.jpg',
			'/images/ad11/ad11_8.jpg',
		],
		price: 'TK  76,500',
		condition: 'Used',
		brand: 'Bajaj',
		model: 'Platina',
		edition: '2018',
		features: [],
		description: 'Bajaj Platina 2018',
		category: 'Bike',
		subCategory: 'Vehicles',
		userId: 1,
	},
	{
		id: 12,
		title: 'Mazda MPV MICROBUS 2003',
		date: 'Posted on 18 Nov 10:36 am, Mohammadpur, Dhaka',
		images: [
			'/images/ad12/ad12_1.jpg',
			'/images/ad12/ad12_2.jpg',
			'/images/ad12/ad12_3.jpg',
			'/images/ad12/ad12_4.jpg',
			'/images/ad12/ad12_5.jpg',
		],
		price: 'TK  700,000',
		condition: 'Used',
		brand: 'Mazda',
		model: 'MPV MICROBUS',
		edition: '2003',
		features: [],
		description: 'Mazda MPV MICROBUS 2003',
		category: 'Car',
		subCategory: 'Vehicles',
		userId: 2,
	},
];

export const users = [
	{
		id: 1,
		name: 'Shahin',
		email: 'user01@gmail.com',
		password: '123456',
		phone: '0178987654',
		address: {
			street: 'Dhaka',
			city: 'Dhaka',
			country: 'Bangladesh',
			zip: '1234',
		},
	},
	{
		id: 2,
		name: 'Manik',
		email: 'user02@gmail.com',
		password: '123456',
		phone: '0178987654',
		address: {
			street: 'Sylhet',
			city: 'Sylhet',
			country: 'Bangladesh',
			zip: '1234',
		},
	},
	{
		id: 3,
		name: 'Sumon',
		email: 'user03@gmail.com',
		password: '123456',
		phone: '0178987654',
		address: {
			street: 'Sunamgnaj',
			city: 'Sunamgnaj',
			country: 'Bangladesh',
			zip: '1234',
		},
	},
];
